-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2023-01-12 20:04:14 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE pr_autor (
    id_autora NUMBER(3) NOT NULL,
    imie      VARCHAR2(20),
    nazwisko  VARCHAR2(30) NOT NULL
);

ALTER TABLE pr_autor ADD CONSTRAINT autor_pk PRIMARY KEY ( id_autora );

CREATE TABLE pr_egzemplarz (
    id_egzemplarza NUMBER(5) NOT NULL,
    status         VARCHAR2(20) NOT NULL,
    nazwa_ksiazki  VARCHAR2(40) NOT NULL,
    id_nosnika     NUMBER(1) NOT NULL
);

ALTER TABLE pr_egzemplarz ADD CONSTRAINT egzemplarz_pk PRIMARY KEY ( id_egzemplarza );

CREATE TABLE pr_gatunek (
    id_gatunku    NUMBER(2) NOT NULL,
    nazwa_gatunku VARCHAR2(20) NOT NULL
);

ALTER TABLE pr_gatunek ADD CONSTRAINT gatunek_pk PRIMARY KEY ( id_gatunku );

CREATE TABLE pr_ksiazka (
    nazwa_ksiazki VARCHAR2(40) NOT NULL,
    ocena_ksiazki NUMBER(2) NOT NULL,
    id_gatunku    NUMBER(2) NOT NULL
);

ALTER TABLE pr_ksiazka ADD CONSTRAINT ksiazka_pk PRIMARY KEY ( nazwa_ksiazki );

CREATE TABLE pr_nosnik (
    id_nosnika    NUMBER(1) NOT NULL,
    nazwa_nosnika VARCHAR2(20) NOT NULL
);

ALTER TABLE pr_nosnik ADD CONSTRAINT nosnik_pk PRIMARY KEY ( id_nosnika );

CREATE TABLE pr_osoba (
    id_osoby     NUMBER(4) NOT NULL,
    imie         VARCHAR2(20) NOT NULL,
    nazwisko     VARCHAR2(20) NOT NULL,
    kod_pocztowy VARCHAR2(6) NOT NULL,
    miejscowosc  VARCHAR2(30) NOT NULL,
    adres        VARCHAR2(40) NOT NULL
);

ALTER TABLE pr_osoba ADD CONSTRAINT osoba_pk PRIMARY KEY ( id_osoby );

CREATE TABLE pr_preferencje (
    id_gatunku     NUMBER(2) NOT NULL,
    id_osoby       NUMBER(4) NOT NULL,
    id_autora      NUMBER(3),
    id_preferencji NUMBER(4) NOT NULL
);

ALTER TABLE pr_preferencje ADD CONSTRAINT preferencje_pk PRIMARY KEY ( id_preferencji );

CREATE TABLE pr_role (
    id_autora     NUMBER(3) NOT NULL,
    nazwa_ksiazki VARCHAR2(40) NOT NULL,
    rola          VARCHAR2(20) NOT NULL
);

ALTER TABLE pr_role ADD CONSTRAINT relation_12_pk PRIMARY KEY ( id_autora,
                                                                nazwa_ksiazki );

CREATE TABLE pr_wypozyczenie (
    id_wypozyczenia    NUMBER(5) NOT NULL,
    koszt_wypozyczenia NUMBER(8, 2) NOT NULL,
    data_wypozyczenia  DATE NOT NULL,
    data_oddania       DATE NOT NULL,
    kara               NUMBER(8, 2),
    id_osoby           NUMBER(4) NOT NULL,
    id_egzemplarza     NUMBER(5) NOT NULL
);

ALTER TABLE pr_wypozyczenie ADD CONSTRAINT wypozyczenie_pk PRIMARY KEY ( id_wypozyczenia );

ALTER TABLE pr_egzemplarz
    ADD CONSTRAINT egzemplarz_ksiazka_fk FOREIGN KEY ( nazwa_ksiazki )
        REFERENCES pr_ksiazka ( nazwa_ksiazki );

ALTER TABLE pr_egzemplarz
    ADD CONSTRAINT egzemplarz_nosnik_fk FOREIGN KEY ( id_nosnika )
        REFERENCES pr_nosnik ( id_nosnika );

ALTER TABLE pr_ksiazka
    ADD CONSTRAINT ksiazka_gatunek_fk FOREIGN KEY ( id_gatunku )
        REFERENCES pr_gatunek ( id_gatunku );

ALTER TABLE pr_preferencje
    ADD CONSTRAINT preferencje_autor_fk FOREIGN KEY ( id_autora )
        REFERENCES pr_autor ( id_autora );

ALTER TABLE pr_preferencje
    ADD CONSTRAINT preferencje_gatunek_fk FOREIGN KEY ( id_gatunku )
        REFERENCES pr_gatunek ( id_gatunku );

ALTER TABLE pr_preferencje
    ADD CONSTRAINT preferencje_osoba_fk FOREIGN KEY ( id_osoby )
        REFERENCES pr_osoba ( id_osoby );

ALTER TABLE pr_role
    ADD CONSTRAINT role_autor_fk FOREIGN KEY ( id_autora )
        REFERENCES pr_autor ( id_autora );

ALTER TABLE pr_role
    ADD CONSTRAINT role_ksiazka_fk FOREIGN KEY ( nazwa_ksiazki )
        REFERENCES pr_ksiazka ( nazwa_ksiazki );

ALTER TABLE pr_wypozyczenie
    ADD CONSTRAINT wypozyczenie_egzemplarz_fk FOREIGN KEY ( id_egzemplarza )
        REFERENCES pr_egzemplarz ( id_egzemplarza );

ALTER TABLE pr_wypozyczenie
    ADD CONSTRAINT wypozyczenie_osoba_fk FOREIGN KEY ( id_osoby )
        REFERENCES pr_osoba ( id_osoby );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                             0
-- ALTER TABLE                             19
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
