DELETE PR_WYPOZYCZENIE;
DELETE PR_EGZEMPLARZ;
DELETE PR_NOSNIK;
DELETE PR_ROLE;
DELETE PR_KSIAZKA;
DELETE PR_PREFERENCJE;
DELETE PR_GATUNEK;
DELETE PR_AUTOR;
DELETE PR_OSOBA;

DROP TABLE PR_WYPOZYCZENIE;
DROP TABLE PR_EGZEMPLARZ;
DROP TABLE PR_NOSNIK;
DROP TABLE PR_ROLE;
DROP TABLE PR_KSIAZKA;
DROP TABLE PR_PREFERENCJE;
DROP TABLE PR_GATUNEK;
DROP TABLE PR_AUTOR;
DROP TABLE PR_OSOBA;



